version: '3.8'
services:
  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=act
      - POSTGRES_USER=paul
      - POSTGRES_PASSWORD=123123123
